In [1]:
'''To create an ndarray, we can pass a list, tuple or any array-like object into the array(
method, and it will be converted into an ndarray:'''

import numpy as np 
arr=np.array([1,2,3,4,5]) #creating array
print(arr)
print(type(arr)) #cheak type of arr

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
print(np.__version__) #cheak numpy version

1.21.5


In [3]:
#use tuple to create numpy array
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [4]:
#Create a 2-D array containing the values 1,2,3,4,5 and 5,6,7,8,9:
arr=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [5]:
#Create a 1-D array containing the values 1,2,3,4,5:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 a
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many di
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
d = np.array([[[1, 2, 3]]])
print(d.ndim)

3


In [9]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [10]:
#access array element using indexing
arr = np.array([1, 2, 3, 4])
print(arr[1])
print(arr[2] + arr[3]) #add two element in array using indexing

2
7


In [11]:
arr = np.array([1, 'rahul'])
print(arr)
print(arr[0] + arr[1])

['1' 'rahul']
1rahul


In [12]:
#accessing of 2D-array element
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  2
5th element on 2nd row:  10


In [13]:
#Access 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) #Access the third element of the second array of the first array:

6


In [14]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


### Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2]) #step: skip one element
print(arr[::2]) #skip one elemrnt of entire array

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [16]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr[len(arr):0:-1])
print(arr[len(arr)::-1])
print(arr[::-1])
print(arr[:-2:-1])
print(arr[len(arr)-1::-1])


[7 6 5 4 3 2 1]
[7 6 5 4 3 2 1 0]
[7 6 5 4 3 2 1 0]
[7]
[7 6 5 4 3 2 1 0]


In [17]:
#Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0, 0:6])
print(arr[0:2, 2]) #from both element return 2nd element
print(arr[0:2, 1:4]) 

[7 8 9]
[1 2 3 4 5]
[3 8]
[[2 3 4]
 [7 8 9]]


### Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.
```
i - integer
b - boolean 
u - unsigned integer 
f - float 
c - complex float 
m - timedelta 
M - datetime 
O - object 
S - string 
U - unicode string 
V - fixed chunk of memory for other type ( void )
```

In [18]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

<U6
int64


In [19]:
arr = np.array(['apple', 'banana', 'i am 18 characters'])
# space allocated is equal to largest character string in array
print(arr.dtype)

<U18


In [20]:
#create a array with data type stirng
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [21]:
#Create an array with data type 4 bytes integer:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [22]:
#Create an array with data type 4 bytes integer:
arr = np.array([1, 2, 3, 4], dtype='i8')
print(arr)
print(arr.dtype)

[1 2 3 4]
int64


In [23]:
#create a array with data type stirng
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr[0])
print(int(arr[0]))
int_arr = [int(v) for v in arr]
print(int_arr)

[b'1' b'2' b'3' b'4']
b'1'
1
[1, 2, 3, 4]


### Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer

In [24]:
#change data type float into integer
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)
newarr = arr.astype('int')
print(newarr)
print(newarr.dtype)

float64
[1 2 3]
int64


In [25]:
#change data type integer to float
arr = np.array([1, 2, 3])
print(arr.dtype)
newarr = arr.astype('float')
print(newarr)
print(newarr.dtype)

int64
[1. 2. 3.]
float64


In [26]:
#change data type float into integer
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

float64
[1 2 3]
int32


### The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and anychanges made to the original array will affect the view.

In [27]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)
print(arr == x)
print(arr is x)

[42  2  3  4  5]
[1 2 3 4 5]
[False  True  True  True  True]
False


In [28]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)
print(arr == x)
print(arr is x)

[42  2  3  4  5]
[42  2  3  4  5]
[ True  True  True  True  True]
False


In [29]:
arr = np.array([1, 2, 3, 4, 5])
x = arr
arr[0] = 42
print(arr)
print(x)
print(arr == x)
print(arr is x)

[42  2  3  4  5]
[42  2  3  4  5]
[ True  True  True  True  True]
True


### Get the Shape of an Array

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [30]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [31]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr.shape)

(2, 2, 3)


### Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [32]:
'''Convert the following 1-D array with 12 elements into a 2-D array.
The outermost dimension will have 4 arrays, each with 3 elements:'''
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(6, 2)
print(newarr)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
newarr = arr.reshape(4, 2, 2)
print(newarr)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [35]:
''''Convert the following 1-D array with 12 elements into a 3-D array.
The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:'''
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Iterating Arrays

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [36]:
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
 print(x)

[1 2 3]
[4 5 6]


In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for row in arr:
    for e in row:
        print(e)

1
2
3
4
5
6


In [39]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [40]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [41]:
# 3-d array using nditer() method
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [42]:
# Iterate through every scalar element of the 2D array skipping 1 element:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [43]:
# Sometimes we require corresponding index of the element while iterating, the ndenumerate(
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [44]:
#initializing numpy array with same number
arr=np.full((2,6),-1)
print(arr)

[[-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]]


In [45]:
#initializing numpy array within a range
arr=np.arange(10,20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [46]:
arr=np.arange(10,50,5)
print(arr)

[10 15 20 25 30 35 40 45]


In [47]:
# generate random number in array
arr=np.random.randint(1,100,5)
print(arr)

[10 12 79 81 67]


### Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [49]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [50]:
arr1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
arr = np.concatenate((arr1, arr2), axis=2)
print(arr)


[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


### Using Stack Function

In [51]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [52]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [53]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [54]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### numpy intersection and difference

In [55]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,8])
np.intersect1d(arr1,arr2)

array([3, 4, 5])

In [56]:
np.setdiff1d(arr1,arr2) #return uniq element from arr1

array([1, 2])

In [57]:
np.setdiff1d(arr2,arr1) #return uniq element from arr2

array([6, 8])

### Addition of numpy array

In [58]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,8])
a=np.sum([arr1,arr2])
print(a)

41


In [59]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,8])
a=np.sum([arr1,arr2], axis=0)
print(a)

[ 4  6  8 10 13]


In [60]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,8])
a=np.sum([arr1,arr2], axis=1)
print(a)

[15 26]


### numpy array mathematics

In [61]:
#basic Addition
arr=np.array([10,20,30])
arr=arr+1
print(arr)

[11 21 31]


In [62]:
#basic subtraction
arr=np.array([10,20,30])
arr=arr-1
print(arr)

[ 9 19 29]


In [63]:
#basic multiplication
arr=np.array([10,20,30])
arr=arr*2
print(arr)

[20 40 60]


In [64]:
#basic division
arr=np.array([10,20,30])
arr=arr/2
print(arr)

[ 5. 10. 15.]


In [65]:
arr=np.array([10,20,30])
np.mean(arr)

20.0

In [66]:
arr=np.array([10,20,30])
np.median(arr)

20.0

In [67]:
arr=np.array([10,20,30])
np.std(arr) 

8.16496580927726

In [68]:
arr=np.array([10,20,30])
np.save('myarray', arr)
newary=np.load('myarray.npy')
print(newary)

[10 20 30]


### Splitting NumPy Arrays

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [69]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
new_arr=np.array_split(arr,3) # divide above array into 3 parts
print(new_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [70]:
#splititng 2D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [71]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
# newarr = np.hsplit(arr, 3)
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [72]:
#             0,1,2,3,4,5,6
arr=np.array([1,2,3,4,5,6,4])
x=np.where(arr==4) # return indexes where the value is 4:
print(x)

(array([3, 6]),)


In [73]:
# Find the indexes where the indexes are even:
arr=np.array([1,2,3,4,5,6,4])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 6]),)


In [74]:
arr=np.array([1,2,3,4,5,6,4])
x=np.where(arr%2==0, arr, -1)
print(x)

[-1  2 -1  4 -1  6  4]


In [75]:
# Find the indexes where the values are odd:
arr=np.array([1,2,3,4,5,6,4])
x=np.where(arr%2==1)
print(x)

(array([0, 2, 4]),)


In [76]:
# Find the indexes where the value 7 should be inserted:
arr = np.array([6, 7, 8, 9, 12, 20])
x = np.searchsorted(arr, 19)
print(x)


5


In [77]:
# Find the indexes where the value 7 should be inserted, starting from the right:
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


### Sorting Arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [78]:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


### Filtering Arrays

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list. If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [79]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [80]:
# Create a filter array that will return only values higher than 42:
import numpy as np
arr = np.array([41, 42, 43, 44])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
    # if the element is higher than 42, set the value to True, otherwise False:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [81]:
# Create a filter array that will return only even elements from the original array:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
 # if the element is completely divisble by 2, set the value to True, otherwise False
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [82]:
# Create a filter array that will return only values higher than 42:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [83]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[arr % 2 == 0])

[2 4 6]
